In [2]:
import numpy as np

### Zero Dimension Tensor

In [13]:
Zerod_tensor = np.array(1)
print(Zerod_tensor)
Zerod_tensor.ndim

1


0

### One Dimension Tensor

In [14]:
Oned_tensor = np.array([1,2,3,4,5])
print(Oned_tensor)
Oned_tensor.ndim

[1 2 3 4 5]


1

#### Two Dimension Tensor

In [18]:
Twod_Tensor = np.array([[1,2,3],[3,2,1]])
print(Twod_Tensor)
Twod_Tensor.ndim

[[1 2 3]
 [3 2 1]]


2

#### Three Dimension Tensor

In [26]:
Threed_Tensor = np.array([[[1,2,3],[12,3,4],[1,2,3]]])
print(Threed_Tensor)
Threed_Tensor.ndim


[[[ 1  2  3]
  [12  3  4]
  [ 1  2  3]]]


3

#### Four Dimension Tensor

In [28]:
fourd_tensor = np.array([
    [
    [
        [1,2,3],
        [0,98,6]
        ]
        ]

    ])
print(fourd_tensor)
fourd_tensor.ndim

[[[[ 1  2  3]
   [ 0 98  6]]]]


4