# Voting Ensemble

In [103]:
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression,LogisticRegression,Lasso,Ridge
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.datasets import load_breast_cancer
import seaborn as sns
import pandas as pd
import numpy as np

In [104]:
df = sns.load_dataset('iris')

In [105]:
df['species'] = LabelEncoder().fit_transform(df['species'])

In [106]:
df.sample()

sepal_length  sepal_width  petal_length  petal_width  species
10           5.4          3.7           1.5          0.2        0

In [107]:
X = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [108]:
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [109]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: species, dtype: int32

In [110]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1)

In [111]:
print(X_train.shape)
print(X_test.shape)

(135, 4)
(15, 4)


In [112]:
clf1 = LogisticRegression(multi_class="multinomial")
clf2 = LinearRegression()
clf3 = DecisionTreeClassifier()

In [113]:
estimator = [('lg',clf1),('lr',clf2),('dt',clf3)]

In [114]:
for est in estimator:
    X = cross_val_score(est[1],X_train,y_train,cv=10,scoring='accuracy')
    print(est[0],np.round(np.mean(X),2))

C:\Users\hp\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\hp\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\hp\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\hp\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logisti

lg 0.96
lr nan


C:\Users\hp\AppData\Roaming\Python\Python311\site-packages\sklearn\model_selection\_validation.py:1000: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_scorer.py", line 139, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_scorer.py", line 376, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Roaming\Python\Python311\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py", line 222,

dt 0.94


# Voting Classification Ensemble

In [115]:
from sklearn.ensemble import VotingClassifier,VotingRegressor

#### Hard Voting

In [116]:
vc = VotingClassifier(estimators=estimator,voting='hard')
X = cross_val_score(est[1],X_train,y_train,cv=10,scoring='accuracy')
print(np.round(np.mean(X),2))

0.95


#### Soft Voting

In [117]:
vc = VotingClassifier(estimators=estimator,voting='soft')
X = cross_val_score(est[1],X_train,y_train,cv=10,scoring='accuracy')
print(np.round(np.mean(X),2))

0.94


# Weights

In [118]:
for i in range(1,4):
    for j in range(1,4):
        for k in range(1,4):
            vc = VotingClassifier(estimators=estimator,voting='soft',weights=[i,j,k])
            X = cross_val_score(est[1],X_train,y_train,cv=10,scoring='accuracy')
            print(f"for i={i},j={j},k={k}",np.round(np.mean(X),2))

for i=1,j=1,k=1 0.94
for i=1,j=1,k=2 0.94
for i=1,j=1,k=3 0.95
for i=1,j=2,k=1 0.94
for i=1,j=2,k=2 0.93
for i=1,j=2,k=3 0.94
for i=1,j=3,k=1 0.94
for i=1,j=3,k=2 0.94
for i=1,j=3,k=3 0.93
for i=2,j=1,k=1 0.94
for i=2,j=1,k=2 0.95
for i=2,j=1,k=3 0.95
for i=2,j=2,k=1 0.94
for i=2,j=2,k=2 0.94
for i=2,j=2,k=3 0.94
for i=2,j=3,k=1 0.95
for i=2,j=3,k=2 0.94
for i=2,j=3,k=3 0.94
for i=3,j=1,k=1 0.94
for i=3,j=1,k=2 0.94
for i=3,j=1,k=3 0.93
for i=3,j=2,k=1 0.95
for i=3,j=2,k=2 0.93
for i=3,j=2,k=3 0.94
for i=3,j=3,k=1 0.94
for i=3,j=3,k=2 0.94
for i=3,j=3,k=3 0.94


# Voting Regressor Ensemble

In [119]:
X,y = load_breast_cancer(return_X_y=True)

In [120]:
print(X)
print(y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [121]:
reg1 = DecisionTreeRegressor()
reg2 = Lasso()
reg3 = Ridge()
reg4 = LinearRegression()

In [122]:
reg_estimator = [('DTR',reg1),('las',reg2),('rid',reg3),('Ln',reg4)]

In [123]:
for estimator in reg_estimator:
    scores = cross_val_score(estimator[1],X,y,scoring='r2',cv=10)
    print(estimator[0],np.round(np.mean(scores),2))

DTR 0.66
las 0.44
rid 0.67
Ln 0.68


In [124]:
vr = VotingRegressor(estimators=reg_estimator)

In [125]:
scores = cross_val_score(vr,X,y,scoring='r2',cv=10)
print("Voting Regressor",np.round(np.mean(scores),2))

Voting Regressor 0.73
