In [1]:
import numpy as np

# Creating Numpy Array

In [2]:
arr1 = np.array([1,2,3,4,5])

In [3]:
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr2= np.array([[1,2,3,4,5],[5,4,3,2,1]])

In [5]:
print(arr2)
print(type(arr2))

[[1 2 3 4 5]
 [5 4 3 2 1]]
<class 'numpy.ndarray'>


In [15]:
arr3 = np.ones((5,5))
print(arr3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
arr4 =  np.zeros((4,4))
print(arr4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr6 = np.arange(0,20,2)
arr6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [90]:
arr7 = np.linspace(-1,1,50)
arr7

array([-1.        , -0.95918367, -0.91836735, -0.87755102, -0.83673469,
       -0.79591837, -0.75510204, -0.71428571, -0.67346939, -0.63265306,
       -0.59183673, -0.55102041, -0.51020408, -0.46938776, -0.42857143,
       -0.3877551 , -0.34693878, -0.30612245, -0.26530612, -0.2244898 ,
       -0.18367347, -0.14285714, -0.10204082, -0.06122449, -0.02040816,
        0.02040816,  0.06122449,  0.10204082,  0.14285714,  0.18367347,
        0.2244898 ,  0.26530612,  0.30612245,  0.34693878,  0.3877551 ,
        0.42857143,  0.46938776,  0.51020408,  0.55102041,  0.59183673,
        0.63265306,  0.67346939,  0.71428571,  0.75510204,  0.79591837,
        0.83673469,  0.87755102,  0.91836735,  0.95918367,  1.        ])

In [28]:
arr8 = arr7.copy()

In [29]:
arr8

array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
       32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ])

In [30]:
arr1.shape

(5,)

In [31]:
arr1.ndim

1

In [32]:
arr1.itemsize

4

In [33]:
arr1.dtype

dtype('int32')

In [36]:
arr1.astype('float')

array([1., 2., 3., 4., 5.])

In [37]:
arr1.dtype

dtype('int32')

In [43]:
three_dim_arr = np.array([[[1,2],[1,2]]])

In [44]:
three_dim_arr.ndim

3

In [45]:
three_dim_arr.shape

(1, 2, 2)

In [46]:
three_dim_arr.itemsize

4

In [47]:
three_dim_arr.dtype

dtype('int32')

In [50]:
arr12 = np.arange(36).reshape(3,12)

In [51]:
arr12

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [59]:
arr12[0:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [62]:
arr12[0:2,0:4]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [63]:
for i in arr12:
    print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[12 13 14 15 16 17 18 19 20 21 22 23]
[24 25 26 27 28 29 30 31 32 33 34 35]


In [68]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35


In [69]:
arr12


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [70]:
arr12.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [72]:
arraA = np.array([[12,78,98],[9,98,65]])

In [74]:
arraB = np.array([[1,8,98],[9,9,6]])

In [77]:
a = np.hstack((arraA,arraB))

In [78]:
a

array([[12, 78, 98,  1,  8, 98],
       [ 9, 98, 65,  9,  9,  6]])

In [79]:
b = np.vstack((arraA,arraB))

In [80]:
b

array([[12, 78, 98],
       [ 9, 98, 65],
       [ 1,  8, 98],
       [ 9,  9,  6]])

In [82]:
arr12

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [85]:
arrT = arr12.transpose()

In [86]:
arrT

array([[ 0, 12, 24],
       [ 1, 13, 25],
       [ 2, 14, 26],
       [ 3, 15, 27],
       [ 4, 16, 28],
       [ 5, 17, 29],
       [ 6, 18, 30],
       [ 7, 19, 31],
       [ 8, 20, 32],
       [ 9, 21, 33],
       [10, 22, 34],
       [11, 23, 35]])

In [87]:
arrT[[0,5,8]]# Fancy Indexing

array([[ 0, 12, 24],
       [ 5, 17, 29],
       [ 8, 20, 32]])